import {
  DroneTelemetry,
  SearchCell,
  AIDetection,
  HazardZone,
  AlertItem,
  TimelineEvent,
  CommsMessage,
  SystemComponentHealth,
  Waypoint,
  SafetyCheckItem,
  MissionReportData,
} from '../types';

export const BASE_COORDINATES = {
  lat: 28.47468,
  lng: 77.47648,
  altitude: 42,
};

export const INITIAL_TELEMETRY: DroneTelemetry = {
  id: 'DRONE-01',
  name: 'SankatSathi Hawk-1 (DTC Greater Noida)',
  model: 'Quadcopter Hexa-Rotor Heavy SAR',
  autopilot: 'PX4 Autopilot v1.14.2 (NuttX)',
  companionComputer: 'NVIDIA Jetson Nano 4GB (JetPack 4.6.1)',
  status: 'ONLINE',
  mode: 'AUTO',
  battery: 78,
  voltage: 22.8,
  current: 14.4,
  altitude: 42,
  groundSpeed: 6.4,
  verticalSpeed: 0.1,
  heading: 48,
  latitude: 28.47468,
  longitude: 77.47648,
  homeLatitude: 28.47350,
  homeLongitude: 77.47520,
  distanceFromHome: 210,
  satellites: 15,
  gpsFix: 'LOCKED',
  signalStrength: 92,
  signalRssi: -62,
  aiStatus: 'ONLINE',
  aiInferenceMs: 42,
  aiFps: 28,
  cameraStatus: 'STREAMING',
  thermalStatus: 'NOT_INSTALLED',
  obstacleDistance: 3.8,
  obstacleStatus: 'CLEAR',
  roll: 2.1,
  pitch: -3.4,
  yaw: 48.0,
  cpuUsage: 48,
  gpuUsage: 76,
  temperature: 46.2,
  mavlinkHeartbeat: true,
  mavlinkLatencyMs: 32,
  mavlinkPacketDropRate: 0.2,
  missionTimeSeconds: 480, // 8 mins in
};

export const FLEET_DRONES: Array<{
  id: string;
  name: string;
  type: string;
  status: 'ONLINE' | 'STANDBY' | 'OFFLINE';
  battery: number;
  gps: string;
  signal: number;
  mode: string;
  mission: string;
  payload: string;
  location: string;
}> = [
  {
    id: 'DRONE-01',
    name: 'Hawk-Alpha (NDRF / DTC Deployment)',
    type: 'Hexacopter SAR AI Payload',
    status: 'ONLINE',
    battery: 78,
    gps: '15 Sat (RTK Lock)',
    signal: 92,
    mode: 'AUTO (Grid Search)',
    mission: 'SAR-2026-09-07-001',
    payload: 'RGB 4K + Laser LiDAR + Jetson',
    location: '28.4747° N, 77.4765° E (Delhi Technical Campus)',
  },
  {
    id: 'DRONE-02',
    name: 'Hawk-Bravo (NDRF Scout)',
    type: 'Quadcopter Fast Scout',
    status: 'STANDBY',
    battery: 98,
    gps: '14 Sat (Ready)',
    signal: 99,
    mode: 'STANDBY',
    mission: 'QUEUED: KP-III Sector D Backup',
    payload: 'Dual RGB Optical Zoom',
    location: 'DTC Campus Helipad 2 (Knowledge Park-III)',
  },
  {
    id: 'DRONE-03',
    name: 'Hawk-Charlie (Heavy Lift)',
    type: 'Heavy Lift / Drop Pod',
    status: 'OFFLINE',
    battery: 45,
    gps: 'Standby / Docked',
    signal: 0,
    mode: 'CHARGING',
    mission: 'MAINTENANCE_DOCK',
    payload: 'Medical First-Aid Supply Drop Pod',
    location: 'Mobile Command Unit C3 (Knowledge Park-III)',
  },
];

// 16 Grid cells around Delhi Technical Campus & Knowledge Park-III, Greater Noida
// Center: ~ 28.47468 N, 77.47648 E
export const INITIAL_SEARCH_CELLS: SearchCell[] = [
  { id: 'A1', row: 'A', col: 1, bounds: [[28.4772, 77.4730], [28.4772, 77.4752], [28.4757, 77.4752], [28.4757, 77.4730]], status: 'SEARCHED', riskLevel: 'LOW', coveragePercent: 100, detectionsCount: 1, searchedAt: '14:04' },
  { id: 'A2', row: 'A', col: 2, bounds: [[28.4772, 77.4752], [28.4772, 77.4774], [28.4757, 77.4774], [28.4757, 77.4752]], status: 'SEARCHED', riskLevel: 'HIGH', coveragePercent: 100, detectionsCount: 2, searchedAt: '14:08' },
  { id: 'A3', row: 'A', col: 3, bounds: [[28.4772, 77.4774], [28.4772, 77.4796], [28.4757, 77.4796], [28.4757, 77.4774]], status: 'SEARCHED', riskLevel: 'MEDIUM', coveragePercent: 100, detectionsCount: 1, searchedAt: '14:12' },
  { id: 'A4', row: 'A', col: 4, bounds: [[28.4772, 77.4796], [28.4772, 77.4818], [28.4757, 77.4818], [28.4757, 77.4796]], status: 'SEARCHED', riskLevel: 'LOW', coveragePercent: 100, detectionsCount: 0, searchedAt: '14:16' },

  { id: 'B1', row: 'B', col: 1, bounds: [[28.4757, 77.4730], [28.4757, 77.4752], [28.4742, 77.4752], [28.4742, 77.4730]], status: 'SEARCHED', riskLevel: 'LOW', coveragePercent: 100, detectionsCount: 1, searchedAt: '14:20' },
  { id: 'B2', row: 'B', col: 2, bounds: [[28.4757, 77.4752], [28.4757, 77.4774], [28.4742, 77.4774], [28.4742, 77.4752]], status: 'SEARCHING', riskLevel: 'HIGH', coveragePercent: 68, detectionsCount: 2 }, // Delhi Technical Campus Campus Core
  { id: 'B3', row: 'B', col: 3, bounds: [[28.4757, 77.4774], [28.4757, 77.4796], [28.4742, 77.4796], [28.4742, 77.4774]], status: 'PENDING', riskLevel: 'HIGH', coveragePercent: 0, detectionsCount: 0 },
  { id: 'B4', row: 'B', col: 4, bounds: [[28.4757, 77.4796], [28.4757, 77.4818], [28.4742, 77.4818], [28.4742, 77.4796]], status: 'PENDING', riskLevel: 'MEDIUM', coveragePercent: 0, detectionsCount: 0 },

  { id: 'C1', row: 'C', col: 1, bounds: [[28.4742, 77.4730], [28.4742, 77.4752], [28.4727, 77.4752], [28.4727, 77.4730]], status: 'PENDING', riskLevel: 'LOW', coveragePercent: 0, detectionsCount: 0 },
  { id: 'C2', row: 'C', col: 2, bounds: [[28.4742, 77.4752], [28.4742, 77.4774], [28.4727, 77.4774], [28.4727, 77.4752]], status: 'PENDING', riskLevel: 'HIGH', coveragePercent: 0, detectionsCount: 0 },
  { id: 'C3', row: 'C', col: 3, bounds: [[28.4742, 77.4774], [28.4742, 77.4796], [28.4727, 77.4796], [28.4727, 77.4774]], status: 'PENDING', riskLevel: 'HIGH', coveragePercent: 0, detectionsCount: 0 },
  { id: 'C4', row: 'C', col: 4, bounds: [[28.4742, 77.4796], [28.4742, 77.4818], [28.4727, 77.4818], [28.4727, 77.4796]], status: 'PENDING', riskLevel: 'LOW', coveragePercent: 0, detectionsCount: 0 },

  { id: 'D1', row: 'D', col: 1, bounds: [[28.4727, 77.4730], [28.4727, 77.4752], [28.4712, 77.4752], [28.4712, 77.4730]], status: 'PENDING', riskLevel: 'LOW', coveragePercent: 0, detectionsCount: 0 },
  { id: 'D2', row: 'D', col: 2, bounds: [[28.4727, 77.4752], [28.4727, 77.4774], [28.4712, 77.4774], [28.4712, 77.4752]], status: 'PENDING', riskLevel: 'MEDIUM', coveragePercent: 0, detectionsCount: 0 },
  { id: 'D3', row: 'D', col: 3, bounds: [[28.4727, 77.4774], [28.4727, 77.4796], [28.4712, 77.4796], [28.4712, 77.4774]], status: 'PENDING', riskLevel: 'LOW', coveragePercent: 0, detectionsCount: 0 },
  { id: 'D4', row: 'D', col: 4, bounds: [[28.4727, 77.4796], [28.4727, 77.4818], [28.4712, 77.4818], [28.4712, 77.4796]], status: 'PENDING', riskLevel: 'LOW', coveragePercent: 0, detectionsCount: 0 },
];

export const INITIAL_DETECTIONS: AIDetection[] = [
  {
    id: 'DET-004',
    type: 'PERSON',
    label: 'SURVIVOR #04 (DTC CAMPUS)',
    confidence: 0.94,
    timestamp: '14:32:18',
    latitude: 28.47468,
    longitude: 77.47648,
    altitude: 41.2,
    priority: 'CRITICAL',
    status: 'VERIFIED',
    bbox: [0.32, 0.45, 0.68, 0.62],
    visualAssessment: 'Individual trapped beneath fallen structural beam near Delhi Technical Campus Academic Block void. Visual motion confirmed (arm waving).',
    nearestSafeRouteDistance: 240,
    nearbyHazards: ['Class-A Debris Fire (110m East)', 'Unstable Concrete Slab'],
    assignedTeam: 'NDRF Unit Alpha-4 (Knowledge Park-III)',
    notes: 'Access via Western campus gate recommended to bypass live electrical hazard.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-006',
    type: 'PERSON',
    label: 'SURVIVOR #06 (HOSTEL REFUGE)',
    confidence: 0.96,
    timestamp: '14:26:44',
    latitude: 28.47620,
    longitude: 77.47750,
    altitude: 43.0,
    priority: 'HIGH',
    status: 'RESCUE_DISPATCHED',
    bbox: [0.25, 0.28, 0.58, 0.46],
    visualAssessment: 'Two individuals seated on elevated hostel rooftop refuge in Knowledge Park-III surrounded by standing water.',
    nearestSafeRouteDistance: 320,
    nearbyHazards: ['Standing water (1.1m depth)', 'Submerged debris'],
    assignedTeam: 'NDRF Quick Response Team Echo-1',
    notes: 'High clearance vehicle / boat en-route.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-001',
    type: 'PERSON',
    label: 'SURVIVOR #01',
    confidence: 0.89,
    timestamp: '14:08:12',
    latitude: 28.47680,
    longitude: 77.47380,
    altitude: 40.5,
    priority: 'MEDIUM',
    status: 'RESCUED',
    bbox: [0.4, 0.5, 0.7, 0.65],
    visualAssessment: 'Single adult walking along Knowledge Park sector road away from debris, signal acknowledged by rescue ground team.',
    nearestSafeRouteDistance: 110,
    nearbyHazards: ['Minor glass debris'],
    assignedTeam: 'NDRF Ground Team Alpha',
    notes: 'Extracted safely to Greater Noida Emergency Response Station.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-003',
    type: 'FIRE',
    label: 'FIRE #01',
    confidence: 0.93,
    timestamp: '14:11:05',
    latitude: 28.47280,
    longitude: 77.47820,
    altitude: 42.0,
    priority: 'HIGH',
    status: 'VERIFIED',
    bbox: [0.15, 0.6, 0.55, 0.9],
    visualAssessment: 'Active debris fire with heavy smoke plume propagating northeast across Knowledge Park-III sector C3.',
    nearestSafeRouteDistance: 280,
    nearbyHazards: ['High thermal radiation', 'Toxic smoke plume'],
    assignedTeam: 'Greater Noida Fire Unit Charlie',
    notes: 'Do not approach from downwind sector C3.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-005',
    type: 'DAMAGED_STRUCTURE',
    label: 'STRUCTURAL COLLAPSE #02',
    confidence: 0.91,
    timestamp: '14:18:30',
    latitude: 28.47520,
    longitude: 77.47800,
    altitude: 44.0,
    priority: 'CRITICAL',
    status: 'VERIFIED',
    bbox: [0.3, 0.2, 0.8, 0.8],
    visualAssessment: 'Multi-story concrete institutional frame partially collapsed. Severe void spaces detected.',
    nearestSafeRouteDistance: 450,
    nearbyHazards: ['Imminent secondary collapse risk', 'Exposed rebar'],
    notes: 'Search cameras and acoustic listening probes deployed by team.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-007',
    type: 'ELECTRICAL_HAZARD',
    label: 'EXPOSED 11kV POWER LINE',
    confidence: 0.88,
    timestamp: '14:22:15',
    latitude: 28.47650,
    longitude: 77.47550,
    altitude: 41.5,
    priority: 'HIGH',
    status: 'VERIFIED',
    bbox: [0.45, 0.1, 0.65, 0.35],
    visualAssessment: 'Fallen transformer & severed 11kV cables resting on flooded access road near DTC Gate 2.',
    nearestSafeRouteDistance: 180,
    nearbyHazards: ['Electrocution zone 30m radius'],
    notes: 'Power grid isolation command requested to NPCL (Noida Power Company Ltd).',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-008',
    type: 'FLOOD',
    label: 'WATER INUNDATION #01',
    confidence: 0.95,
    timestamp: '14:24:50',
    latitude: 28.47180,
    longitude: 77.47400,
    altitude: 42.0,
    priority: 'MEDIUM',
    status: 'VERIFIED',
    bbox: [0.5, 0.1, 0.95, 0.7],
    visualAssessment: 'Submerged street and ground floor access paths, water depth approx 1.1m - 1.4m.',
    nearestSafeRouteDistance: 95,
    nearbyHazards: ['Waterborne contamination', 'Submerged vehicles'],
    notes: 'Inflatable boat corridor designated.',
    droneId: 'DRONE-01',
  },
  {
    id: 'DET-002',
    type: 'DEBRIS',
    label: 'ROADWAY BLOCKED #01',
    confidence: 0.87,
    timestamp: '14:09:40',
    latitude: 28.47580,
    longitude: 77.47480,
    altitude: 40.0,
    priority: 'MEDIUM',
    status: 'VERIFIED',
    bbox: [0.35, 0.4, 0.65, 0.8],
    visualAssessment: 'Knowledge Park-III avenue obstructed by overturned container and fallen trees.',
    nearestSafeRouteDistance: 140,
    nearbyHazards: ['Heavy vehicle blockage'],
    notes: 'Earth-mover JCB dispatched to clear path.',
    droneId: 'DRONE-01',
  },
];

export const HAZARD_ZONES: HazardZone[] = [
  {
    id: 'HZ-01',
    type: 'FIRE',
    title: 'KP-III Zone Alpha Fire Perimeter',
    severity: 'HIGH',
    latitude: 28.47280,
    longitude: 77.47820,
    radiusMeters: 140,
    polygon: [[28.4735, 77.4775], [28.4736, 77.4790], [28.4720, 77.4792], [28.4718, 77.4777]],
    description: 'Active debris fire with thermal radiation hazard in Knowledge Park-III.',
    detectedAt: '14:11:05',
    isActive: true,
  },
  {
    id: 'HZ-02',
    type: 'FLOOD',
    title: 'Knowledge Park Sector C Inundation',
    severity: 'MEDIUM',
    latitude: 28.47180,
    longitude: 77.47400,
    radiusMeters: 200,
    polygon: [[28.4728, 77.4730], [28.4730, 77.4752], [28.4705, 77.4755], [28.4703, 77.4732]],
    description: 'Water depth 1.1m - 1.4m; high clearance / boat response required.',
    detectedAt: '14:24:50',
    isActive: true,
  },
  {
    id: 'HZ-03',
    type: 'ELECTRICAL_HAZARD',
    title: '11kV Live Cable Danger (Near DTC Gate 2)',
    severity: 'CRITICAL',
    latitude: 28.47650,
    longitude: 77.47550,
    radiusMeters: 80,
    description: 'Severed live electrical cables submerged on access boulevard.',
    detectedAt: '14:22:15',
    isActive: true,
  },
  {
    id: 'HZ-04',
    type: 'DAMAGED_STRUCTURE',
    title: 'Pancaked Concrete Frame Zone',
    severity: 'CRITICAL',
    latitude: 28.47520,
    longitude: 77.47800,
    radiusMeters: 100,
    description: 'Extreme secondary collapse danger. Acoustic listening team only.',
    detectedAt: '14:18:30',
    isActive: true,
  },
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'ALT-101',
    title: 'SURVIVOR DETECTED (CONF: 94%)',
    description: 'Survivor #04 detected at Delhi Technical Campus Sector B2 near structural void. Immediate rescue triage needed.',
    category: 'CRITICAL',
    timestamp: '14:32:18',
    droneId: 'DRONE-01',
    latitude: 28.47468,
    longitude: 77.47648,
    acknowledged: false,
    relatedDetectionId: 'DET-004',
    actionRequired: 'Dispatch NDRF Triage Team to DTC Campus',
  },
  {
    id: 'ALT-102',
    title: 'CRITICAL HAZARD: 11kV CABLE EXPOSED',
    description: 'Live powerline breach detected in KP-III Sector A2 near DTC Gate 2. 30m exclusion perimeter established.',
    category: 'HIGH',
    timestamp: '14:22:15',
    droneId: 'DRONE-01',
    latitude: 28.47650,
    longitude: 77.47550,
    acknowledged: true,
    relatedDetectionId: 'DET-007',
  },
  {
    id: 'ALT-103',
    title: 'ACTIVE FIRE HAZARD IN SECTOR C3',
    description: 'Thermal bloom detected near Plot 28 boundary. Plume moving towards search perimeter.',
    category: 'HIGH',
    timestamp: '14:11:05',
    droneId: 'DRONE-01',
    latitude: 28.47280,
    longitude: 77.47820,
    acknowledged: true,
    relatedDetectionId: 'DET-003',
  },
  {
    id: 'ALT-104',
    title: 'SEARCH SECTOR B1 COMPLETED',
    description: '100% optical sweep completed with zero unresolved anomalies.',
    category: 'INFO',
    timestamp: '14:20:00',
    droneId: 'DRONE-01',
    acknowledged: true,
  },
  {
    id: 'ALT-105',
    title: 'BATTERY ADVISORY (78%)',
    description: 'Drone battery within nominal operating curve. Estimated remaining search endurance: 18 mins.',
    category: 'INFO',
    timestamp: '14:30:00',
    droneId: 'DRONE-01',
    acknowledged: true,
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  { id: 'TL-1', time: '14:00:00', timestamp: Date.now() - 32 * 60000, title: 'Autonomous Mission Initiated', description: 'Drone-01 launched from Delhi Technical Campus Helipad Alpha. Autopilot entered AUTO_MISSION mode.', type: 'TAKEOFF' },
  { id: 'TL-2', time: '14:04:12', timestamp: Date.now() - 28 * 60000, title: 'Grid Sector A1 Completed', description: 'Initial lawn-mower sweep of Sector A1 completed with 100% coverage.', type: 'GRID_CELL' },
  { id: 'TL-3', time: '14:08:12', timestamp: Date.now() - 24 * 60000, title: 'Survivor #01 Detected & Geo-Tagged', description: 'Edge AI detected person in Sector A2 (89% conf). Lat 28.4768, Lng 77.4738.', type: 'DETECTION', severity: 'MEDIUM', coordinates: [28.4768, 77.4738] },
  { id: 'TL-4', time: '14:11:05', timestamp: Date.now() - 21 * 60000, title: 'Hazard #01 Detected (Fire)', description: 'Thermal plume & flame detected in Sector C3. Geo-tagged & risk map updated.', type: 'HAZARD', severity: 'HIGH', coordinates: [28.4728, 77.4782] },
  { id: 'TL-5', time: '14:18:30', timestamp: Date.now() - 14 * 60000, title: 'Structural Collapse Tagged', description: 'Pancaked institutional structure identified. High hazard alert emitted.', type: 'HAZARD', severity: 'CRITICAL', coordinates: [28.4752, 77.4780] },
  { id: 'TL-6', time: '14:24:50', timestamp: Date.now() - 8 * 60000, title: 'Survivor #06 Detected (Hostel Refuge)', description: 'AI detected 2 stranded individuals on flooded rooftop. Confidence 96%.', type: 'DETECTION', severity: 'HIGH', coordinates: [28.4762, 77.4775] },
  { id: 'TL-7', time: '14:26:10', timestamp: Date.now() - 6 * 60000, title: 'NDRF Unit Dispatched', description: 'Rescue Team Echo-1 dispatched to Survivor #06 coordinates in Knowledge Park-III.', type: 'DISPATCH' },
  { id: 'TL-8', time: '14:32:18', timestamp: Date.now() - 1 * 60000, title: 'Critical Survivor #04 Geo-Tagged (DTC)', description: 'Individual trapped under beam near Delhi Technical Campus identified. Urgent medical triage alert issued.', type: 'DETECTION', severity: 'CRITICAL', coordinates: [28.47468, 77.47648] },
];

export const INITIAL_COMMS: CommsMessage[] = [
  { id: 'CM-1', time: '14:00:15', sender: 'DRONE-01', senderRole: 'Autopilot PX4', message: 'Takeoff successful from DTC Campus Helipad. Transitioned to AUTO mode.', type: 'INFO' },
  { id: 'CM-2', time: '14:04:15', sender: 'AI_CORE', senderRole: 'NVIDIA Jetson Nano', message: 'Vision pipeline running at 28 FPS. Object detection active. Sector A1 clear.', type: 'INFO' },
  { id: 'CM-3', time: '14:08:20', sender: 'AI_CORE', senderRole: 'NVIDIA Jetson Nano', message: 'ALERT: Potential person detected at [28.4768, 77.4738]. Confidence: 89%.', type: 'ALERT' },
  { id: 'CM-4', time: '14:09:00', sender: 'COMMAND_GCS', senderRole: 'Operator NDRF-01', message: 'Target verified on camera feed. Logging Survivor #01. Team Alpha assigned.', type: 'COMMAND' },
  { id: 'CM-5', time: '14:11:10', sender: 'DRONE-01', senderRole: 'Autopilot PX4', message: 'Hazard perimeter established for Fire #01. Waypoints offset to maintain 50m standoff.', type: 'INFO' },
  { id: 'CM-6', time: '14:26:20', sender: 'RESCUE_ALPHA', senderRole: 'Ground Team Leader', message: 'Team Alpha acknowledges Survivor #06 coordinates in Knowledge Park-III.', type: 'ACK' },
  { id: 'CM-7', time: '14:32:25', sender: 'AI_CORE', senderRole: 'NVIDIA Jetson Nano', message: 'CRITICAL: High confidence survivor trapped at Delhi Technical Campus [28.47468, 77.47648].', type: 'ALERT' },
];

export const SYSTEM_COMPONENTS: SystemComponentHealth[] = [
  {
    name: 'PX4 Flight Controller',
    role: 'Flight Management & Motor Control',
    hardware: 'Holybro Pixhawk 6X / NuttX OS',
    status: 'HEALTHY',
    latencyMs: 4,
    details: 'Dual IMU redundancy nominal, EKF3 state estimator healthy, failsafes armed',
    isFlightCritical: true,
  },
  {
    name: 'Companion Computer',
    role: 'Edge AI Inference & Geo-Tagging',
    hardware: 'NVIDIA Jetson Nano 4GB (JetPack 4.6)',
    status: 'HEALTHY',
    latencyMs: 42,
    details: 'TensorRT YOLOv8 SAR model running @ 28 FPS, GPU core clock 921 MHz',
    isFlightCritical: false, // Edge AI failure does NOT affect PX4 flight safety
  },
  {
    name: 'MAVLink Telemetry Bridge',
    role: 'Bi-directional Micro-Air-Vehicle Link',
    hardware: 'High-speed UART / UDP Telemetry Radio 915MHz',
    status: 'HEALTHY',
    latencyMs: 32,
    details: 'Heartbeat active (1Hz), Packet drop 0.2%, Baud rate 921600',
    isFlightCritical: true,
  },
  {
    name: 'GNSS / RTK GPS',
    role: 'Centimeter Precision Positioning',
    hardware: 'u-blox ZED-F9P RTK Multi-Band',
    status: 'HEALTHY',
    latencyMs: 12,
    details: '15 Satellites locked, HDOP: 0.72, Fix: 3D Fix RTK Float/Fixed',
    isFlightCritical: true,
  },
  {
    name: 'RGB Optical Camera',
    role: 'Primary Search & AI Visual Feed',
    hardware: 'Sony IMX477 12.3MP Sensor (1080p60)',
    status: 'HEALTHY',
    latencyMs: 22,
    details: 'H.264 RTP stream active, Auto-exposure tuned for disaster lighting',
    isFlightCritical: false,
  },
  {
    name: 'Thermal Infrared Camera',
    role: 'Night / Thermal Signature Detection',
    hardware: 'FLIR Boson 640 Thermal Core (Optional Expansion)',
    status: 'OFFLINE',
    details: 'Sensor not installed in current prototype (Expansion Slot #2 ready)',
    isFlightCritical: false,
  },
  {
    name: 'Front Rangefinder',
    role: 'Forward Collision Avoidance (Single Axis)',
    hardware: 'TFmini-S Micro LiDAR (0.1m - 12m)',
    status: 'HEALTHY',
    latencyMs: 8,
    details: 'Front obstacle distance: 3.8m (CLEAR). Caution: 1D front plane only.',
    isFlightCritical: false,
  },
  {
    name: 'Ground Control Station Link',
    role: 'Encrypted Command & Control Uplink',
    hardware: 'SankatSathi Command GCS (WPA3-Enterprise)',
    status: 'HEALTHY',
    latencyMs: 18,
    details: 'Signal: 92% (-62 dBm), Encrypted mesh relay active',
    isFlightCritical: true,
  },
];

export const SAFETY_CHECKLIST: SafetyCheckItem[] = [
  { id: 'SC-1', title: 'PX4 Autopilot & Dual IMU Calibration', category: 'AUTOPILOT', status: 'PASS', value: 'EKF3 Healthy (Dual Redundant)', critical: true },
  { id: 'SC-2', title: 'RTK GPS 3D Satellites Lock', category: 'SENSORS', status: 'PASS', value: '15 Satellites (HDOP 0.72)', critical: true },
  { id: 'SC-3', title: 'Power System & LiPo Voltage Check', category: 'AUTOPILOT', status: 'PASS', value: '78% (22.8V / 6S nominal)', critical: true },
  { id: 'SC-4', title: 'MAVLink Telemetry & Heartbeat Sync', category: 'COMMUNICATION', status: 'PASS', value: 'Active (32ms roundtrip)', critical: true },
  { id: 'SC-5', title: 'Edge AI (Jetson Nano) TensorRT Model', category: 'AI_PAYLOAD', status: 'PASS', value: 'SAR-YOLOv8 Loaded @ 28 FPS', critical: false },
  { id: 'SC-6', title: 'Camera Stream RTSP & Sensor Exposure', category: 'SENSORS', status: 'PASS', value: '1080p 30FPS H.264 Active', critical: false },
  { id: 'SC-7', title: 'Geofence Boundaries & Safe RTL Altitude', category: 'ENVIRONMENT', status: 'PASS', value: 'RTL Set @ 45m AGL (Clear)', critical: true },
  { id: 'SC-8', title: 'Obstacle Sensing (Front Laser Rangefinder)', category: 'SENSORS', status: 'PASS', value: 'LiDAR Online (3.8m clear)', critical: false },
];

export const DEFAULT_MISSION_REPORT: MissionReportData = {
  missionId: 'SAR-2026-09-07-001',
  missionName: 'Disaster Reconnaissance - Delhi Technical Campus & Knowledge Park-III',
  operationType: 'Autonomous Disaster Reconnaissance & Survivor Geo-Tagging',
  startTime: '14:00:00 IST',
  endTime: '14:32:18 IST (Active)',
  durationFormatted: '32m 18s',
  totalAreaKm2: 3.6,
  areaCoveredKm2: 2.4,
  coveragePercent: 67,
  cellsCompleted: 6,
  totalCells: 16,
  survivorsDetected: 3,
  survivorsVerified: 2,
  hazardsDetected: 5,
  highRiskZonesCount: 4,
  batteryConsumedPercent: 22,
  distanceFlownKm: 4.8,
  maxAltitudeMeters: 45.0,
  status: 'IN_PROGRESS',
  keyDetections: INITIAL_DETECTIONS,
  sitrepSummary: `MISSION SITUATION REPORT (SITREP) - SAR-2026-09-07-001
LOCATION: Delhi Technical Campus (DTC), Plot No. 28/1, Knowledge Park-III, Greater Noida, UP 201306
Status: ACTIVE AUTONOMOUS RECONNAISSANCE
Search Area: 3.6 km² | Coverage: 67% (6/16 cells complete)
Survivors Identified: 3 (1 Rescued, 1 Rescue Dispatched, 1 Critical Trapped at DTC Campus)
Hazards Cataloged: 5 (1 Active Fire, 1 11kV Power Line, 1 Structure Collapse, 2 Inundations)
Key Recommendation: Prioritize immediate heavy lifting gear for Survivor #04 [28.47468° N, 77.47648° E] trapped under structural beam at Delhi Technical Campus Academic Block; bypass eastern fire perimeter via Sector B1 safe corridor.`,
};
